name: Test DNS Script

on: [push, pull_request]

jobs:
  test-script:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x ./dns.sh

    - name: Run the script
      run: ./dns.sh 2

    - name: Check the DNS change
      run: |
        current_dns=$(networksetup -getdnsservers Wi-Fi)
        echo "Current DNS servers: $current_dns"
        if [ "$current_dns" == "There aren't any DNS Servers set on Wi-Fi." ]; then
          echo "DNS servers not set."
          exit 1
        fi
